### ISSUE TITLE
The container should be set to the same timezone than external machine

### ISSUE THREAD

**Issue by facundobatista** [canonical/craft-providers#103]
This is so the timestamps in the logs from the host and from inside the container do not have different hours.

**Comment by mr-cal** [comment]
Great idea!  

I can confirm LXD instances default to UTC time, whereas Multipass instances are set to the host's timezone.

I think the timezone should be set in `bases.buildd.setup()` and `bases.buildd.warmup()`.

(CRAFT-1624)
