### ISSUE TITLE
Provide additional actions

### ISSUE THREAD

**Issue by jugmac00** [canonical/craft-providers#114]
Similar to `from craft_providers.actions.snap_installer` it would be great to have additional actions to 
- update `/etc/apt/sources.list`
- install packages via `apt`

This may be related to #90

**Comment by jugmac00** [comment]
The issue with updating the sources has become more important as due to the deb822 changes which changed the format and the location of the configuration format.

cc @mr-cal  Is this something you could implement this cycle? Or do we need to apply workarounds in lpci ourselves?
see https://bugs.launchpad.net/lpci/+bug/2068868

**Comment by mr-cal** [comment]
For the request to install packages via `apt`, this can be done when creating a base with the `packages` parameter:

From https://git.launchpad.net/lpcraft/tree/lpci/providers/_lxd.py?id=ec6238ebfd71f1be359dbe5b472e3c18970cd07a#n305, you could provide the `apt` packages you want installed:

```
        base_configuration = LPCIBuilddBaseConfiguration(
            alias=alias, environment=environment, hostname=instance_name, packages=["git", "ubuntu-pro", ... ]
        )
```

For updating `/etc/apt/sources.list`, can you give some more details on what you need?
I'm wondering if a generic solution for editing files will be more useful than something specialized for `/etc/apt/sources.list`.  Would completing https://github.com/canonical/craft-providers/issues/132 provide a solution for you?

**Comment by mr-cal** [comment]
Ping @jugmac00

**Comment by jugmac00** [comment]
> For updating /etc/apt/sources.list, can you give some more details on what you need?

This is about adding a new source -which was just adding a line until recently, but with deb822 this got more complex.

The question is whether this could be handled by craft-providers or by lpci? What's your take on that, @mr-cal?

It looks like @andersson1234 would like to include handling of the different apt formats in lpci.
https://code.launchpad.net/~andersson123/lpci/+git/lpci/+merge/470016
(lines 58-88 of the diff).

Let's come to an agreement before we continue either way.

FWIW, the new format looks like
```
Types: deb
URIs: http://archive.ubuntu.com/ubuntu/
Suites: noble noble-updates noble-backports
Components: main restricted universe multiverse
```

**Comment by andersson1234** [comment]
For some nice documentation on deb822, see
https://repolib.readthedocs.io/en/latest/deb822-format.html
and
https://forums.debian.net/viewtopic.php?t=138415

**Comment by mr-cal** [comment]
Hey @andersson1234 and @jugmac00,

After discussing with @tigarmo and @cmatsuoka, we don't think this belongs in craft-providers.  However, craft-archives may be a good solution for you.  We use it for our applications and it's compatible with the deb822 format.

For more information, see the [project](https://github.com/canonical/craft-archives/), [documentation](https://canonical-craft-archives.readthedocs-hosted.com/en/latest/index.html), [integration tests](https://github.com/canonical/craft-archives/blob/main/tests/integration/repo/test_installer.py), and [how it is used](https://github.com/canonical/craft-application/blob/4049a021f906a9b99d2e3d46292ca9f60db34b3d/craft_application/util/repositories.py#L30).

**Comment by jugmac00** [comment]
@mr-cal this looks very interesting. @andersson1234 What do you think?

**Comment by jugmac00** [comment]
@mr-cal Thanks for pointing out to craft-archives... I think for now it makes sense to use a lightweight approach @andersson1234 proposed in https://code.launchpad.net/~andersson123/lpci/+git/lpci/+merge/470016
