### ISSUE TITLE
execute more than one command at a time

### ISSUE THREAD

**Issue by jugmac00** [canonical/craft-providers#115]
Hey,

I'd like to know if there is a way to execute more than one command at once for e.g. via `LXDInstance.execute_run`.

I need to execute a number of commands. In the case there is a failure, I do not care which command failed, but only that the whole thing failed.

Currently I'd need to create a couple of blocks like this...

```python
with emit.open_stream(
    f"Running {update_sources_list}"
) as stream:
    proc = instance.execute_run(
        update_sources_list,
        cwd=remote_cwd,
        env=environment,
        stdout=stream,
        stderr=stream,
    )
```

I'd like to pass in a number of commands at once.

As `command` is a list of command parts, is this even possible? Would I need to pass in ; or && or would I need to create a command string which already combines the commands?

Or is there another way?

Thank you.

**Comment by facundobatista** [comment]
Hello! I'm -0 to add a new functionality and a "different way of doing things" if the same can be resolved with a couple of lines of code.

For example, for your case, what about doing...

```
lot_of_commands = [..., ]
with emit.open_stream("Running lot of commands") as stream:
    for cmd in lot_of_commands:
        proc = instance.execute_run(
            cmd,
            cwd=remote_cwd,
            env=environment,
            stdout=stream,
            stderr=stream,
        )
```

Which would be the problem with that? Thanks!

**Comment by jugmac00** [comment]
Thanks - I think that is a viable solution.
