### ISSUE TITLE
Contributing documentation is not complete

### ISSUE THREAD

**Issue by jugmac00** [canonical/craft-providers#131]
Hi,

I sadly saw that you deleted the tox configuration file.

Instead of just running `tox -e py310` to run the tests, I now needed to figure out to run the tests.

So I went to the README.md, found the following section...

```
## Running tests

To run all tests in the suite run:

make tests
```

So I did as advised...

```
❯ make tests
black --check --diff setup.py craft_providers tests
All done! ✨ 🍰 ✨
81 files would be left unchanged.
codespell setup.py craft_providers tests
make: codespell: Command not found
make: *** [Makefile:74: test-codespell] Error 127
```

So, after that I checked the other make commands ... there must be one to set up the dev environment, right?

No :-/

Next thing I read the Makefile... ok, there is really no command to set up a dev environment.

Next I read `setup.py` and found the `test` and the `dev` extras, so I ...

- created a virtual environment
```
virtualenv venv -p python3.10
```

- installed the dev extras
```
pip install .[dev]
```

And finally was able to run the tests...

```
make tests
....
```

Though actually, this did not run the tests - at least not at the beginning, but the linters oO

When I now want to build the docs, I cannot run `tox -e docs`, but I need to do the whole ceremony again :-/

As you clearly indicated that you do not like the tox workflow, it would be great though to make contributions a bit easier.

You could either update the contribution documentation or create a make target which creates a dev environment.

I am good now, but maybe you could smoothen the process for future contributors.

Thanks for considering!

**Comment by jugmac00** [comment]
Oh... it continues...

```
pytest tests/integration
========================================================================= test session starts ==========================================================================
platform linux -- Python 3.8.10, pytest-7.1.2, pluggy-1.0.0
rootdir: /home/jugmac00/Projects/craft-providers, configfile: setup.cfg
plugins: mock-3.7.0, logassert-7, subprocess-1.4.1
collected 117 items                                                                                                                                                    

tests/integration/actions/test_snap_installer.py ss...                                                                                                           [  4%]
tests/integration/lxd/test_installer.py .s.ss                                                                                                                    [  8%]
tests/integration/lxd/test_launcher.py ...F.........                                                                                                             [ 19%]
tests/integration/lxd/test_lxc.py ........                                                                                                                       [ 26%]
tests/integration/lxd/test_lxd.py [sudo] password for jugmac00: 
```

So I both have a test failure and a test for which I need sudo?

This looks like it is not suggested to run the test suite on a laptop directly.

Ok, now I could dig into `.github/workflows/tests.yaml` to figure out what I need to do to be able run the tests.. but now I ran out of time :-(

**Comment by mr-cal** [comment]
Thanks, Jurgen!  We definitely need to improve the contributing documentation.  Same as https://github.com/canonical/craft-providers/issues/221, tox will be returning to craft-providers.

The unit test that requires sudo is not good.  I'm going to make a separate issue for that.

**Comment by mr-cal** [comment]
Marking this ticket as resolved due to a number of improvements!
- Added a [`HACKING.rst`](https://github.com/canonical/craft-providers/blob/main/HACKING.rst) doc
- Added `tox`, removed `Makefile`
- Stopped running tests that require `sudo` by default (#328)
