### ISSUE TITLE
Provide a way to access content from an in-instance file

### ISSUE THREAD

**Issue by facundobatista** [canonical/craft-providers#138]
We should have a context manager that brings the content of an in-instance ("remote") file to a external ("local") temp file, cleaning that file later.

It should receive the instance executor and the path in the instance; it should provide the local path of the temp file.

It should have a `missing_ok=False` option to ignore if the file is not in the instance.

**Comment by mr-cal** [comment]
`temporarily_pull_file()` method added in https://github.com/canonical/craft-providers/pull/139
