### ISSUE TITLE
Use pre-built containers to speed up the first charmcraft pack

### ISSUE THREAD

**Issue by jdkandersson** [canonical/craft-providers#142]
When running the `charmcraft pack` command for the first time, it looks like charmcraft creates a lxd container to pack the charm. It also looks like this container is built locally. There is potentially an opportunity to just pull an image from a remote source that is already setup to be able to facilitate the charm building.

**Comment by mr-cal** [comment]
Thanks for the suggestion!  In the last year, we've made some substantial improvements to the mechanisms for creating and reusing LXD containers.  The local setup continues to get more efficient.

The setup steps can be divided into 3 categories:
1. Generic setup (e.g. enabling `systemd-resolved`)
2. Charmcraft-specific setup (e.g. installing the same version of charmcraft from the local host into the container)
3. Container-specific setup (e.g. configuring a unique hostname)

Only items in the first category can be done before distributing the image.  Those steps are short and relatively quick, so we're going to continue to use the public images for the foreseeable future.
