### ISSUE TITLE
changelog is not included in the documentation

### ISSUE THREAD

**Issue by jugmac00** [canonical/craft-providers#221]
I wanted to look up some recent API changes, but I could not easily find your changelog, as it is not included on https://craft-providers.readthedocs.io/en/latest/

I finally found it inside the docs folder, so it is there, but just not included.

sphinx warns when an existing file is not included, and imho it is a good idea to enable strict mode for sphinx, which turns all warnings into errors.

Currently there are a lot of warnings, which hide real issues like the missing changelog:
```
build succeeded, 172 warnings.
```

Currently, building the documentation locally is rather cumbersome, at least since you dropped the tox configuration file.

Now, instead of running just `tox -e docs` I need to
- create a virtualenv
- look up the dependencies I need to install in the setup file
- run make

If you ever consider to re-introduce tox, similar to https://github.com/canonical/craft-cli/blob/4436263bc1cdb4cb940372c25a42959a73695a4a/tox.ini#L13-L14 please let me know, I'd volunteer to create a PR (at least for the docs step for now).

**Comment by mr-cal** [comment]
Thanks for the report!  We need to improve the documentation for craft-providers.

Breaking this into a few parts:
1. changelog isn't in the documentation
2. documentation building and testing isn't part of the CI
3. there are lots of documentation warnings
4. there isn't an easy way to build the docs without tox

Issue #1 is going to be done.  We've triaged it and are tracking it internally with CRAFT-1309.

Issues 2, 3, and 4 are bigger issues.  There is an effort to re-align the tooling used by the *craft applications and libraries.  This includes using tox!  It's been a big challenge and we're not ready yet for craft-providers to inherit the new tooling.  I will keep you updated when we're ready, I will love your help on a tox migration.

**Comment by mr-cal** [comment]
I'm marking this ticket as completed as all 4 issues above have been addressed with #296.

The documentation itself is still sparse, but that is a separate issue.
