### ISSUE TITLE
changelog for 1.8.0 is missing

### ISSUE THREAD

**Issue by jugmac00** [canonical/craft-providers#233]
I noticed that as we faced a regression with the latest release 1.8.0 and I wanted to have a look what additionally changed in that release.

**Comment by mr-cal** [comment]
I'm sorry for your troubles!

This is an unfortunate side-effect of using the OneFlow branching model and the missing [changelogs in the docs](https://github.com/canonical/craft-providers/issues/221).

@cmatsuoka - Do you have a strategy for keeping the changelog updated across the release branches in craft-parts?

**Comment by mr-cal** [comment]
Update - the root cause is me not understanding how oneflow works...

**Comment by mr-cal** [comment]
Fixed, thanks for raising this!
