### ISSUE TITLE
LXD integration tests fail on Ubuntu 22.04

### ISSUE THREAD

**Issue by mr-cal** [canonical/craft-providers#270]
## Overview

The integration test [`test_push_file_io`](https://github.com/canonical/craft-providers/blob/660921e77d155eae512153119f7974d3f93e0b7a/tests/integration/lxd/test_lxd_instance.py#L56) works on 20.04 runners but does not work on 22.04  runners nor in my 22.04 environment.

### Details

The tests fail when they expect a `ubuntu` user to exist in the LXD instance.  I'm not sure why this works in 20.04.  

### Logs
```
> pytest tests/integration/lxd/test_lxd_instance.py::test_push_file_io


E           craft_providers.lxd.errors.LXDError: Failed to create file '/tmp/file-test.txt' in instance 'itest-YTMGLLZR'.
E           * Command that failed: 'lxc --project default exec local:itest-YTMGLLZR -- chown ubuntu:ubuntu /tmp/file-test.txt'
E           * Command exit code: 1
E           * Command standard error output: b'chown: invalid user: \xe2\x80\x98ubuntu:ubuntu\xe2\x80\x99\n'

craft_providers/lxd/lxd_instance.py:202: LXDError
```

**Comment by lengau** [comment]
Digging into this a bit:

On my machine (22.04 with LXD 5.13), the reusable instance doesn't have a user called ubuntu.

If I change the image in `tmp_instance` to 18.04, 20.04 or 22.04, everything works fine.

Do we need to support Ubuntu 16.04 instances anymore?
