### ISSUE TITLE
craft-providers incompatible with python 3.11

### ISSUE THREAD

**Issue by mr-cal** [canonical/craft-providers#272]
Craft-providers does not work with python 3.11.  

While Python 3.11 compatibility is not an urgent requirement, it is a stepping stone towards ubuntu 24.04 + python 3.12 compatibility.

**Comment by syu-w** [comment]
Wait, I use it just fine. What error you get?

**Comment by lengau** [comment]
@mr-cal I'm also having a hard time making it fail under 3.11. I made #279 though so the CI will run with 3.11 and 3.12. (We can get rid of 3.11 once 3.12 fully released.)

Leaving this open though so we can discuss and maybe find a reproducer.

**Comment by mr-cal** [comment]
No, I was mistaken and am not having any issues with 3.11!
