### ISSUE TITLE
lxd test_init should not run by default since it requires sudo

### ISSUE THREAD

**Issue by lengau** [canonical/craft-providers#321]
tests/integration/lxd/test_lxd.py::test_init

**Comment by mr-cal** [comment]
Similar to https://github.com/canonical/craft-providers/issues/321

I am +1 for a `pytest.skip`.  Perhaps `pytest.skipif(not os.environ.get("CI"))`?

**Comment by lengau** [comment]
Yep, this is a dupe of #222
