### ISSUE TITLE
lxd: race condition when running multiple instances of craft-providers

### ISSUE THREAD

**Issue by mr-cal** [canonical/craft-providers#341]
### Overview

New race condition reported from charmcraft: https://github.com/canonical/charmcraft/issues/1132

### Details

This is similar to an issue from 2022: 
- https://github.com/canonical/charmcraft/issues/554
- #96 
- #158

The charm's CI pipeline runs multiple instances of charmcraft in parallel and create a race condition when executing lxc commands.  In the prior bug, the race condition was caused by `lxc remote add`.  In this new report, the race condition is caused by `lxc project create`.

### Logs

https://github.com/canonical/kfp-operators/actions/runs/5399918594/jobs/9807754324

```
Traceback (most recent call last):
  File "/home/runner/work/kfp-operators/kfp-operators/tests/integration/test_bundle.py", line 39, in test_build_and_deploy
    built_charms = await ops_test.build_charms(*charms_to_build.values())
  File "/home/runner/work/kfp-operators/kfp-operators/.tox/bundle-integration/lib/python3.8/site-packages/pytest_operator/plugin.py", line 1028, in build_charms
    charms = await asyncio.gather(
  File "/home/runner/work/kfp-operators/kfp-operators/.tox/bundle-integration/lib/python3.8/site-packages/pytest_operator/plugin.py", line 1011, in build_charm
    raise RuntimeError(
RuntimeError: Failed to build charm /home/runner/work/kfp-operators/kfp-operators/charms/kfp-viz:
Packing the charm.
Launching environment to pack for base name='ubuntu' channel='20.04' architectures=['amd64'] (may take a while the first time but it's reusable)
charmcraft internal error: LXDError(brief="Failed to create project 'charmcraft'.", details='* Command that failed: \'lxc --project charmcraft project create local:charmcraft\'\n* Command exit code: 1\n* Command standard error output: b\'Error: Failed creating project "charmcraft": Failed adding database record: This "projects" entry already exists\\n\'', resolution=None)
Full execution log: '/home/runner/.local/state/charmcraft/log/charmcraft-20230628-102516.095719.log'
```

### Solution

Craft-providers can use the same race condition handling that was re-used for the prior issue (PR linked above).

**Comment by beliaev-maksim** [comment]
hi @mr-cal @sergiusens 
this becomes really burning since all CIs in kubeflow where we have several charms start to fail

**Comment by mr-cal** [comment]
Tracking with CRAFT-1849

**Comment by lengau** [comment]
There's a third race condition seen in https://github.com/canonical/charmcraft/issues/1138 where lxc fails when trying to copy from a base that's still being created. [Example run](https://github.com/canonical/kfp-operators/actions/runs/5456837818/jobs/9930395637#step:7:80)

**Comment by beliaev-maksim** [comment]
@lengau @mr-cal 
I think initial issue is fixed, now the new one appears:

```
charmcraft internal error: LXDError(brief="Failed to copy instance 'local:charmcraft-knative-serving-162750-0-0-amd64' to 'local:base-instance-charmcraft-buildd-base-v10-07bde40a62a827cdc5a4'.", details='* Command that failed: \'lxc --project charmcraft copy local:charmcraft-knative-serving-162750-0-0-amd64 local:base-instance-charmcraft-buildd-base-v10-07bde40a62a827cdc5a4\'\n* Command exit code: 1\n* Command standard error output: b\'Error: Failed creating instance record: Instance is busy running a "create" operation\\n\'', resolution=None)
```

**Comment by sergiusens** [comment]
https://github.com/canonical/charmcraft/issues/1138

**Comment by sergiusens** [comment]
We are going to go down with locking, current proposal is https://pypi.org/project/pid/
