### ISSUE TITLE
New release to add latest changes, especially support for oracular

### ISSUE THREAD

**Issue by jugmac00** [canonical/craft-providers#580]
### What needs to get done

Please create a new release.

### Why it needs to get done

Users of lpci cannot build on oracular, as the currently available version on PyPI does not contain the changes to add support of oracular, see https://github.com/canonical/craft-providers/commit/0f0f35d90bc0fe6bd12c62d9bd91749a59316db1

**Comment by mr-cal** [comment]
I'll release today!
