### ISSUE TITLE
Add an option to validate internet access when requesting an instance

### ISSUE THREAD

**Issue by facundobatista** [canonical/craft-providers#87]
When requesting an instance, I want to tell the lib to check for internet access and fail accordingly if not available. This should be done before the instance does any network-related work (e.g. `apt update`).

This should be available and executed no matter if the instance is created or reused.

**Comment by mr-cal** [comment]
I think we can close this now that https://github.com/canonical/craft-providers/pull/189 and https://github.com/canonical/craft-providers/pull/185 have landed!
