### ISSUE TITLE
Suddenly getting charmcraft internal error with charmcraft pack

### ISSUE THREAD

**Issue by PietroPasotti** [canonical/craft-providers#92]
Since today, I am unable to `charmcraft pack` anything. 
What changed since yesterday? Did an `apt upgrade` which bumped `snapd` among other unrelated things and did some old kernel images cleanup (my /boot partition was full). Not sure if that's related, but...

```
lxd: 4.23
charmcraft: 1.4.0
$ snap version                       
snap    2.54.3+20.04.1ubuntu0.1
snapd   2.54.3+20.04.1ubuntu0.1
series  16
ubuntu  20.04
kernel  5.13.0-28-generic
```

Posting this here because the culprit seems to be `craft_providers/lxd/lxc.py", line 121, in config_device_add_disk`
maybe something changed in lxc to the effect that disk-/anything/with/slashes is no longer a valid device name?

[charmcraft-20220223-111023.300160.log](https://github.com/canonical/craft-providers/files/8123542/charmcraft-20220223-111023.300160.log)

apparently an update to the lxd snap changed the validation logic for device names; that update occurred overnight for me.
Related: https://github.com/lxc/lxd/pull/9960/files
`snap revert lxd` fixed this issue.

**Comment by jugmac00** [comment]
Thanks for your detailed support - I faced a similar problem and this saved me some debugging time.

**Comment by facundobatista** [comment]
There was a glitch in the LXD project, for some revisions they were too strict for the device name. This is fixed already, you should get the updates automatically, and the problem should be gone in LXD 4.23 revision 22525 or higher.
